/**
 ******************************************************************************
 * @file      syscalls.c
 * @author    Auto-generated by STM32CubeIDE
 * @brief     STM32CubeIDE Minimal System calls file
 *
 *            For more information about which c-functions
 *            need which of these lowlevel functions
 *            please consult the Newlib libc-manual
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2020-2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/* Includes */
#include <sys/stat.h>
#include <stdlib.h>
#include <errno.h>
#include <stdio.h>
#include <signal.h>
#include <time.h>
#include <sys/time.h>
#include <sys/times.h>


/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));


char *__env[1] = { 0 };
char **environ = __env;


/* Functions */
void initialise_monitor_handles()
{
}

int _getpid(void)
{
  return 1;
}

int _kill(int pid, int sig)
{
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

void _exit (int status)
{
  _kill(status, -1);
  while (1) {}    /* Make sure we hang here */
}

__attribute__((weak)) int _read(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    *ptr++ = __io_getchar();
  }

  return len;
}

__attribute__((weak)) int _write(int file, char *ptr, int len)
{
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++)
  {
    __io_putchar(*ptr++);
  }
  return len;
}

int _close(int file)
{
  (void)file;
  return -1;
}


int _fstat(int file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _isatty(int file)
{
  (void)file;
  return 1;
}

int _lseek(int file, int ptr, int dir)
{
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

int _open(char *path, int flags, ...)
{
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

int _wait(int *status)
{
  (void)status;
  errno = ECHILD;
  return -1;
}

int _unlink(char *name)
{
  (void)name;
  errno = ENOENT;
  return -1;
}

int _times(struct tms *buf)
{
  (void)buf;
  return -1;
}

int _stat(char *file, struct stat *st)
{
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

int _link(char *old, char *new)
{
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

int _fork(void)
{
  errno = EAGAIN;
  return -1;
}

int _execve(char *name, char **argv, char **env)
{
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}

//HAL_TIM_Base_Start(&htim2);		//Timer without interrupt
  //HAL_TIM_Base_Start_IT(&htim3);	//Timer with interrupt

  /*char msg[] = "Hello from STM32 via UART\r\n";	//Basic uart
  HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);*/

  //char rx_data;               // One character
  //char tx_buffer[50];         // Transmit buffer

/*if (HAL_GPIO_ReadPin(GPIOC, GPIO_PIN_13) == GPIO_PIN_RESET) {		//User button led activate
	        HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
	        HAL_Delay(200); // debounce delay
	  }*/
	  /*
	  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_SET);   // LED ON (LED BLINK 500ms)
	  HAL_Delay(500);                                       // Delay 500 ms

	  HAL_GPIO_WritePin(GPIOA, GPIO_PIN_5, GPIO_PIN_RESET); // LED OFF
	  HAL_Delay(500);
	  */
	  /*
	  if (__HAL_TIM_GET_FLAG(&htim2, TIM_FLAG_UPDATE) != RESET)		//Timer without interrupt
	    {
	      __HAL_TIM_CLEAR_FLAG(&htim2, TIM_FLAG_UPDATE);
	      HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5); // Toggle onboard LED
	    }
		*/
	    /* Start counting up from 0 to 9999 at 10 kHz

		Set TIM_FLAG_UPDATE every 1 second

		You can poll that flag in main() and toggle an LED
		*/
	  /*
	  HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);

	  char msg[] = "LED toggled\r\n";
	  HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);

	  HAL_Delay(1000); // Wait 0.1 second //Basic UART
	  */
	  /*STM32 sends: "Type a character: "

		You type a character in your serial terminal.

		STM32 replies with: "You typed: X"

		If you type 'x', the LED toggles.
		*/
/*
	  // Prompt user
	      char msg[] = "Type a character: ";
	      HAL_UART_Transmit(&huart2, (uint8_t*)msg, strlen(msg), HAL_MAX_DELAY);

	      // Receive 1 character (blocking wait)
	      HAL_UART_Receive(&huart2, (uint8_t*)&rx_data, 1, HAL_MAX_DELAY);

	      // Echo back with response
	      snprintf(tx_buffer, sizeof(tx_buffer), "\r\nYou typed: %c\r\n", rx_data);
	      HAL_UART_Transmit(&huart2, (uint8_t*)tx_buffer, strlen(tx_buffer), HAL_MAX_DELAY);

	      // Optional: toggle LED if user types 'x'
	      if (rx_data == 'x')
	      {
	          HAL_GPIO_TogglePin(GPIOA, GPIO_PIN_5);
	          HAL_UART_Transmit(&huart2, (uint8_t*)"LED toggled!\r\n", 14, HAL_MAX_DELAY);
	      }
*/
